### ISSUE TITLE
Cannot join LAN worlds: "Failed to deserialize ingredient..."

### ISSUE THREAD

**Issue by KxttyKxt** [JarHax/IngredientExtensionAPI#1]
Crosspost from CraftTweaker because I installed these at the same time; this mod was an automatically added dependency in CurseForge.

https://github.com/CraftTweaker/CraftTweaker/issues/1524

**Comment by KxttyKxt** [comment]
I have confirmed this is an issue with Ingredient Extension API, as the issue persists with CraftTweaker missing. All information in the CT issue report is still relevant, however.

**Comment by 0xicl33n** [comment]
Same issue here..1.18.2

fabric 0.14.9
fabric-api-0.59.0+1.18.2
CraftTweaker-fabric-1.18.2-9.1.177
IngredientExtensionAPI-fabric-1.18.2-2.0.8

**Comment by rango3526** [comment]
Same issue here in 1.19.2, newest version of this mod as of now. Can't enter servers without removing the mod, which makes REI not work for modded items unfortunately.

EDIT: Actually the server was indeed the problem, it didn't have the mod installed correctly. After the server was fixed, this issue disappeared.

**Comment by Darkhax** [comment]
Please ensure that the host of the LAN server also has the Ingredient Extension API installed. This mod fundamentally changes the network protocol which will prevent any client with this mod from connecting to a LAN or dedicated server without this mod. I've gone through and recreated the game environment from each comment on this thread and was able to join LAN when the LAN host also has the mod installed without issue.

**Comment by Darkhax** [comment]
> EDIT: Actually the server was indeed the problem, it didn't have the mod installed correctly. After the server was fixed, this issue disappeared.

Thanks for letting me know that this resolved the issue.
